### ISSUE TITLE
Add the 'getPagePadding' property to the 'mxGraph' class

### ISSUE THREAD

**Issue by EfrenHerrera** [typed-mxgraph/typed-mxgraph#60] opened 2024-02-08 14:58 UTC
/**
* Hook for subclassers.
*/
getPagePadding(): mxPoint;

**Comment by hungtcs** [comment] 2024-02-18 07:01
Duplicate of https://github.com/typed-mxgraph/typed-mxgraph/issues/62

**Closed as not planned by hungtcs** 2024-02-18 07:01 UTC
