### ISSUE TITLE
Add the 'getPageSize' property to the 'mxGraph' class

### ISSUE THREAD

**Issue by EfrenHerrera** [typed-mxgraph/typed-mxgraph#61] opened 2024-02-08 15:00 UTC
/**
   * Returns the size of the page format scaled with the page size.
   */
  getPageSize(): mxRectangle;

**Comment by hungtcs** [comment] 2024-02-18 07:01
Duplicate of https://github.com/typed-mxgraph/typed-mxgraph/issues/62

**Closed as not planned by hungtcs** 2024-02-18 07:01 UTC
